# Authentication public key (address)
ACCOUNTS = ["GAJVQNMXKW4XL4WYGOGY5IVBUJKWKXYAMHVKG4AKHHY2YRHTTZEMQB6M"]
VERSION = "0.1.0"
# Authentication public key (address)
SIGNING_KEY = "SCBNJQXKOIAFHB4XD3NGLWTR6WTKUZJKVC2OHVNGRSVB2Y2OKLSHKMEQ"
NETWORK_PASSPHRASE = "Test SDF Network ; September 2015"


TRANSFER_SERVER_SEP0024 = "http://localhost:8080/sep24"
WEB_AUTH_ENDPOINT = "http://localhost:8080/auth"


# Add support for USDC
[[CURRENCIES]]
code = "USDC"
issuer = "GC3IQJ5UKKSRTLLN7QEPRHZSVBPG3JRC3MJFUEWPKDZGIE577IQKUXIH"
status = "test"
is_asset_anchored = false
desc = "USD Coin issued by Circle"



[DOCUMENTATION]
ORG_NAME = "NUPAT"
ORG_URL = "https://stellar.org"
ORG_DESCRIPTION = "The Stellar Development Foundation (SDF) is a non-profit organization whose mission is to create equitable access to the global financial system."
