# config/dev.services.yaml
version: 1
platform_server:
  port: 8085
assets:
  type: file
  value: /dev.assets.yaml
data:
  type: postgres
  server: db
  database: platform
  flyway_enabled: true
sep24:
  enabled: true
sep1:
  enabled: true
  toml:
    type: file
    values: /dev.stellar.toml

